package migrator

import (
	"strings"
	"testing"
)

func TestContainsNullByte(t *testing.T) {
	cases := []struct {
		value any
		want  bool
	}{
		{"plain text", false},
		{"embedded\x00nul", true},
		{[]byte("bytes\x00too"), true},
		{[]byte("clean bytes"), false},
		{"\x00", true},
		{"", false},
		{42, false},
		{nil, false},
	}
	for _, testCase := range cases {
		if got := containsNullByte(testCase.value); got != testCase.want {
			t.Fatalf("containsNullByte(%q) = %v, want %v", testCase.value, got, testCase.want)
		}
	}
}

func TestTransformRowsStripsNullBytesFromTextColumns(t *testing.T) {
	m := &Migrator{}
	plans := []columnPlan{
		{name: "note", dataType: "text", kind: kindVerbatimText, nullable: true},
		{name: "payload", dataType: "bytea", kind: kindBytea, nullable: true},
	}
	binary := []byte{0x01, 0x00, 0x02}
	data := [][]any{
		{[]byte("hello\x00world"), binary},
		{"already clean", []byte("no nul")},
	}
	if err := m.transformRows("docs", plans, data); err != nil {
		t.Fatalf("transformRows: %v", err)
	}
	if got := data[0][0]; got != "helloworld" {
		t.Fatalf("text NUL not stripped: got %q", got)
	}
	// Binary-destined values keep NUL bytes untouched.
	if got, ok := data[0][1].([]byte); !ok || string(got) != string(binary) {
		t.Fatalf("bytea value modified: got %v", data[0][1])
	}
	if got := data[1][0]; got != "already clean" {
		t.Fatalf("clean text modified: got %q", got)
	}
}

func TestTransformValueKindTimeDurations(t *testing.T) {
	m := &Migrator{}

	if _, err := m.transformValueKind(kindTime, "time without time zone", "12:30:45"); err != nil {
		t.Fatalf("valid time rejected: %v", err)
	}
	// MySQL TIME(6) delivers fractional seconds; Go's Parse accepts them.
	if _, err := m.transformValueKind(kindTime, "time without time zone", "12:30:45.123456"); err != nil {
		t.Fatalf("fractional time rejected: %v", err)
	}

	for _, duration := range []string{"500:00:00", "838:59:59", "-01:30:00", "24:00:01"} {
		_, err := m.transformValueKind(kindTime, "time without time zone", duration)
		if err == nil {
			t.Fatalf("duration %q unexpectedly accepted", duration)
		}
		if !strings.Contains(err.Error(), "=interval'") {
			t.Fatalf("duration %q error lacks the interval cast hint: %v", duration, err)
		}
	}

	_, err := m.transformValueKind(kindTime, "time without time zone", "not-a-time")
	if err == nil || strings.Contains(err.Error(), "interval") {
		t.Fatalf("garbage value should get the generic error, got: %v", err)
	}
}

func TestIsUnsignedBigintTypeSpellings(t *testing.T) {
	for _, mysqlType := range []string{"bigint(20) unsigned", "bigint unsigned", "BIGINT UNSIGNED", "bigint(20) unsigned zerofill"} {
		if !isUnsignedBigintType(mysqlType) {
			t.Fatalf("%q not recognized as unsigned bigint", mysqlType)
		}
	}
	for _, mysqlType := range []string{"bigint(20)", "bigint", "int unsigned", "int(10) unsigned", "varchar(20)"} {
		if isUnsignedBigintType(mysqlType) {
			t.Fatalf("%q wrongly recognized as unsigned bigint", mysqlType)
		}
	}
}

func TestMapsToPostgresIntegerFamily(t *testing.T) {
	for _, mysqlType := range []string{"bigint(20)", "bigint", "int(11)", "int unsigned", "mediumint(9)", "smallint(6)", "tinyint(4)"} {
		if !mapsToPostgresIntegerFamily(mysqlType) {
			t.Fatalf("%q should map to the integer family", mysqlType)
		}
	}
	for _, mysqlType := range []string{"bigint unsigned", "bigint(20) unsigned", "varchar(36)", "decimal(20,0)"} {
		if mapsToPostgresIntegerFamily(mysqlType) {
			t.Fatalf("%q should not map to the integer family", mysqlType)
		}
	}
}

func TestUnsignedBigintDemotionDrivesColumnDefinition(t *testing.T) {
	// Without a demotion decision, the lossless NUMERIC(20) mapping holds
	// and AUTO_INCREMENT fails closed.
	m := &Migrator{schemaName: "app"}
	_, pgType, err := m.buildColumnDefinition("orders", ColumnInfo{
		Name:  "id",
		Type:  "bigint(20) unsigned",
		Extra: "auto_increment",
	})
	if err == nil {
		t.Fatalf("undemoted unsigned bigint AUTO_INCREMENT should fail, got %s", pgType)
	}

	// With the resolver's data-verified demotion, the same column becomes a
	// BIGINT identity.
	m.unsignedCheck.demote = map[string]bool{unsignedKey("orders", "id"): true}
	def, pgType, err := m.buildColumnDefinition("orders", ColumnInfo{
		Name:  "id",
		Type:  "bigint(20) unsigned",
		Extra: "auto_increment",
	})
	if err != nil {
		t.Fatalf("demoted unsigned bigint AUTO_INCREMENT failed: %v", err)
	}
	if pgType != "BIGINT" {
		t.Fatalf("pgType = %q, want BIGINT", pgType)
	}
	if !strings.Contains(def, "GENERATED BY DEFAULT AS IDENTITY") {
		t.Fatalf("definition %q lacks identity clause", def)
	}

	// Plain unsigned bigint without a decision keeps NUMERIC(20).
	_, pgType, err = m.buildColumnDefinition("orders", ColumnInfo{Name: "counter", Type: "bigint unsigned"})
	if err != nil {
		t.Fatalf("plain unsigned bigint: %v", err)
	}
	if pgType != "NUMERIC(20)" {
		t.Fatalf("pgType = %q, want NUMERIC(20)", pgType)
	}
}

func TestWarnOncePerColumnDeduplicates(t *testing.T) {
	m := &Migrator{}
	if !m.warnOncePerColumn("nul", "docs", "note") {
		t.Fatal("first warning suppressed")
	}
	if m.warnOncePerColumn("nul", "docs", "note") {
		t.Fatal("repeat warning not suppressed")
	}
	if !m.warnOncePerColumn("zero-date", "docs", "note") {
		t.Fatal("different kind wrongly suppressed")
	}
	if !m.warnOncePerColumn("nul", "docs", "other") {
		t.Fatal("different column wrongly suppressed")
	}
}
